### ISSUE TITLE
Unable to use turn on Script

### ISSUE THREAD

**Issue by szymonprz** [hokiebrian/spotify_plus#7]
Turn on device script is not working I got the following error

```
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:287
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 9:54:56 AM (7 occurrences)
Last logged: 10:15:57 AM

[547328799888] SAM0001E - An unhandled exception occured while processing method "GetInformation". HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /zc?action=getInfo&version=2.7.1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3fd24490>: Failed to establish a new connection: [Errno 111] Connection refused'))
[547328799888] Spotify Player device ""bbd1003185d2aa685f2070d544351068b0d71d2a"" was not found in the Spotify Connect device list; verify the device is discoverable via Zeroconf on the local network.
[547328799888] SAM0001E - An unhandled exception occured while processing method "GetInformation". HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /zc?action=getInfo&version=2.7.1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3feab890>: Failed to establish a new connection: [Errno 111] Connection refused'))
[547328799888] SAM0001E - An unhandled exception occured while processing method "GetInformation". HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /zc?action=getInfo&version=2.7.1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3feaaa80>: Failed to establish a new connection: [Errno 111] Connection refused'))
[547328799888] SAM0001E - An unhandled exception occured while processing method "GetInformation". HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /zc?action=getInfo&version=2.7.1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f401d37a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

Here's my script
```
alias: Transfer Spotify Playback to Bose SoundTouch device.
data:
  entity_id: media_player.spotifyplus_myusername
  play: true
  device_id: bbd1003185d2aa685f2070d5443510XXXXXXX
enabled: true
action: spotifyplus.player_transfer_playback
```

Am I doing something wrong?
